Thought.create(content: 'Get rich quick')
Thought.create(content: 'Buy a puppy')
Thought.create(content: 'Return the DVD')
Thought.create(content: 'Borrow the book')
Thought.create(content: 'Read the comics')